server:
  port: 8090

spring:
  application:
    name: checkin-service
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:http://localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:baggage}
    driverClassName: org.postgresql.Driver
    username: ${DB_USER:baggage}
    password: ${DB_PASSWORD:baggage123}
  jpa:
    hibernate:
      ddl-auto: ${DDL_AUTO:update}